# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8abede88daf3d95b2d135cb96e03e7ac340b5603cbdc7fee5674526f3adb3bf6699d4f7986c058f56a36a1558fa0c37cb2a1d1e5e9100a7851c77b39e1355bfd

test:
  secret_key_base: 307c971f385dc3101b4b12530513bf6f860325121f7f00e80a8427ce8c5093778d1ef1e39bf952e94c48d42bda36dfb2eed78c8c4bba0978480dae7fbf5c9352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
